version: "3.7"
services:
  web-service:
    image: "bmuschko/todo-web-service:latest"
    ports:
    - target: 8080
      published: 8080
    networks:
    - todo-net
    volumes:
    - type: volume
      source: todo-vol
      target: /code
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:8080/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  todo-net:

volumes:
  todo-vol: