= ToDo web application

A web application for managing ToDo items based on Spring Boot. This application calls a https://github.com/bmuschko/todo-web-service[RESTful web service] responsible managing the data. The underlying implementation is based on Spring Boot built by Gradle. The provided `Jenkinsfile` defines a build pipeline definition for creating, pushing and deploying a Docker image of the application.

== Running the service locally

Execute the task `bootRun` with the Gradle Wrapper command to bring up the service. Optional arguments can be provided e.g. the server port. The following example starts the application on port 9090.

----
$ ./gradlew bootRun --args='--server.port=9090'
----

You can activate a profile by passing in the relevant environment. The default profile uses a H2 database. The `prod` profile is used for production environments.

The following example uses the development profile.

----
$ ./gradlew bootRun --args='--spring.profiles.active=dev'
----

== Running the service as composed Docker application stack

The provided `docker-compose.yml` file bootstraps the setup of all services required to run the application properly. Run the Docker Compose `up` command to starts the services:

----
$ docker-compose up
----

You can shut down the services with the Docker Compose `down` command:

----
$ docker-compose down
----
